studytodo:
  site:
    author: springRunner
    description: What're your plans today?
  data:
    initialize: true

spring:
  application:
    name: studytodo

  server:
    servlet:
      encoding:
        charset: utf-8
        force: true


logging:
  level:
    '[todoapp]': debug
    web: debug
    sql: debug

